spring.application.name=app

# Server Config
server.port=${PORT}

#MySQL Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Driver
spring.datasource.driver-class-name=${MYSQL_DRIVER}

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${SESSION_TIME}